# fly.toml app configuration file generated for n8n-sanjaya on 2025-08-25T12:17:35+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'n8n-sanjaya'
primary_region = 'sin'

[build]

[env]
  DB_POSTGRESDB_DATABASE = 'n8n'
  DB_POSTGRESDB_SCHEMA = 'public'
  DB_POSTGRESDB_SSL = 'true'
  DB_POSTGRESDB_SSL_MODE = 'require'
  DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED = 'false'
  DB_TYPE = 'postgresdb'
  DB_POSTGRESDB_CONNECTION_TIMEOUT = '30000'
  GENERIC_TIMEZONE = 'Asia/Colombo'
  N8N_BASIC_AUTH_ACTIVE = 'true'
  N8N_DIAGNOSTICS_ENABLED = 'false'
  N8N_HIRING_BANNER_ENABLED = 'false'
  N8N_LOG_LEVEL = 'info'
  N8N_PORT = '5678'
  N8N_PROTOCOL = 'https'
  N8N_RUNNERS_ENABLED = 'true'
  N8N_SECURE_COOKIE = 'true'
  N8N_USER_MANAGEMENT_DISABLED = 'false'
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
  TZ = 'Asia/Colombo'

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
